core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('users.urls')),
    path('empresas/', include('companies.urls')),
    path('investidores/', include('investors.urls')),
    path('', lambda request: redirect('register_company'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investors/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sugestao/', views.sugestions , name='sugestions'),
    path('ver_empresa/<int:id>', views.inspect_company , name='inspect_company'),
    path('realizar_proposta/<int:id>', views.make_proposal , name='make_proposal'),
    path('assinar_contrato/<int:id>', views.sign_contract, name="sign_contract"),
    path('gerenciar_propostas/<int:id>', views.manage_proposals, name="manage_proposals"),
]

companies/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Company(models.Model):
    existence_time_choices = (
        ('-6', 'Menos de 6 meses'),
        ('+6', 'Mais de 6 meses'),
        ('+1', 'Mais de 1 ano'),
        ('+5', 'Mais de 5 anos')
        
    )
    phase_choices = (
        ('I', 'Tenho apenas uma idea'),
        ('MVP', 'Possuo um MVP'),
        ('MVPP', 'Possuo um MVP com clientes pagantes'),
        ('E', 'Empresa pronta para escalar'),
    )
    area_choices = (
        ('ED', 'Ed-tech'),
        ('FT', 'Fintech'),
        ('AT', 'Agrotech'),
        
    )
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=50)
    cnpj = models.CharField(max_length=30)
    site = models.URLField()
    existence_time = models.CharField(max_length=2, choices=existence_time_choices, default='-6')
    description = models.TextField() 
    end_of_capture = models.DateField()
    percentual_equity = models.IntegerField() # Percentual esperado
    phase = models.CharField(max_length=4, choices=phase_choices, default='I')
    area = models.CharField(max_length=3, choices=area_choices)
    target_audience = models.CharField(max_length=3)
    value = models.DecimalField(max_digits=9, decimal_places=2) # Valor total a ser vendido
    pitch = models.FileField(upload_to='pitchs')
    logo = models.FileField(upload_to='logo')

    def __str__(self):
        return f'{self.user.username} | {self.name}'
    
    @property
    def status(self):
        if date.today() > self.end_of_capture:
            return mark_safe('<span class="badge bg-success">Captação finalizada</span>')
        return mark_safe('<span class="badge bg-primary">Em captação</span>')
    
    @property
    def valuation(self):
       return float(f'{(100*self.value) / self.percentual_equity:.2f}')
    

class Document(models.Model):
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=30)
    file = models.FileField(upload_to="documents")

    def __str__(self):
        return self.title
    

class Metrics(models.Model):
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=30)
    value = models.FloatField()

    def __str__(self):
        return self.title

investors/models.py
from django.db import models
from companies.models import Company
from django.contrib.auth.models import User

# Create your models here.
class InvestmentProposal(models.Model):
    status_choices = (
        ('AS', 'Aguardando assinatura'),
        ('PE', 'Proposta enviada'),
        ('PA', 'Proposta aceita'),
        ('PR', 'Proposta recusada')
    )
    value = models.DecimalField(max_digits=9, decimal_places=2)
    percentual = models.FloatField()
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING)
    investor = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=2, choices=status_choices, default='AS')
    selfie = models.FileField(upload_to="selfie", null=True, blank=True)
    rg = models.FileField(upload_to="rg", null=True, blank=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.value)
    
    @property
    def valuation(self):
        return (100 * float(self.value) / self.percentual)

investors/views.py
from django.shortcuts import render, redirect
from companies.models import Company, Document, Metrics
from .models import InvestmentProposal
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages import constants
from django.http import Http404



@login_required
def sugestions(request):    
    areas = Company.area_choices
    if request.method == "GET":
        return render(request, 'sugestions.html', {"areas": areas})
    elif request.method == "POST":
        investor_type = request.POST.get('type')
        area = request.POST.getlist('area')
        value = request.POST.get('value')

        if investor_type == 'C':
            companies = Company.objects.filter(existence_time='+5').filter(phase='E')
        elif investor_type == 'D':
            companies = Company.objects.filter(existence_time__in=['-6', '+6', '+1']).exclude(phase='E')
        elif investor_type == 'G':
            companies = Company.objects.all()

        companies = companies.filter(area__in=area)

        selected_companies = []
        for company in companies:
            percentual = float(value) * 100 / float(company.valuation)
            if percentual >= 1:
                selected_companies.append(company)
                return render(request, 'sugestions.html', {"areas": areas, "companies":selected_companies})


@login_required
def inspect_company(request, id):
    company = Company.objects.get(id=id)
    documents = Document.objects.filter(company=company)
    prop_invest = InvestmentProposal.objects.filter(company=company).filter(status='PA')
    percentual_sold = 0
    for prop in prop_invest:
        percentual_sold += prop.percentual
    
    limiar = (80 * company.percentual_equity) / 100
    concretizado = False
    if percentual_sold >= limiar:
        concretizado =True

    metrics = Metrics.objects.filter(company)

    percentual_disponivel = company.percentual_equity - percentual_sold
    context = {"company": company, "percentual_sold": int(percentual_sold), "concretizado": concretizado, "percentual_disponivel": percentual_disponivel,
               "documents": documents, "metrics": metrics}
    return render(request, 'inspect_company.html', context)


@login_required
def make_proposal(request, id):
    value =request.POST.get('value')
    percentual =request.POST.get('percentual')
    company = Company.objects.get(id=id)

    proposals_accepted = InvestmentProposal.objects.filter(company=company, status='PA')
    total = 0
    for pa in proposals_accepted:
        total += pa.percentual
    
    if total + float(percentual) > company.percentual_equity:
        messages.add_message(request, constants.WARNING, 'O percentual solicitado ultrapassa o percentual máximo')
        return redirect('inspect_company', id)

    valuation = 100 * int(value) / int(percentual)

    if valuation < float(company.valuation / 2):
        messages.add_message(request, constants.WARNING, f'O valuation proposto foi de {valuation:.2f}, o mínimo para a empresa é {int(company.valuation / 2) + 1}')
        return redirect('inspect_company', id)
    
    inv_prop =  InvestmentProposal(
        value=value,
        percentual=percentual,
        company=company,
        investor=request.user
    )
    

    inv_prop.save()
    return redirect('sign_contract', inv_prop.id)



def sign_contract(request, id):
    inv_prop = InvestmentProposal.objects.get(id=id)
    if inv_prop.status != 'AS':
        raise Http404()
    
    if request.method == "GET":
        context ={"id": id, "inv_prop": inv_prop}
        return render(request, 'sign_contract.html', context)
    
    elif request.method == "POST":
        selfie = request.FILES.get('selfie')
        rg = request.FILES.get('rg')

        inv_prop.selfie = selfie
        inv_prop.rg = rg
        inv_prop.status = 'PE'

        inv_prop.save()

        messages.add_message(request, constants.SUCCESS, f'Contrato assinado com sucesso, sua proposta foi enviada a empresa.')
        return redirect('inspect_company', inv_prop.company.id)
    

def manage_proposals(request, id):
    action = request.GET.get('action')

    inv_prop = InvestmentProposal.objects.get(id=id)

    if action == 'accept':
        messages.add_message(request, constants.SUCCESS, 'Proposta aceita')
        inv_prop.status = "PA"
    elif action == "refuse":
        messages.add_message(request, constants.SUCCESS, 'Proposta recusada')
        inv_prop.status = "PR"

    inv_prop.save()
    return redirect('company_details', inv_prop.company.id)

investors/templates/inspect_company.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

<link rel="stylesheet" href="{% static 'businessman/css/list_companies.css' %}">
<link rel="stylesheet" href="{% static 'businessman/css/company_details.css' %}">
<link rel="stylesheet" href="{% static 'users/css/users.css' %}">
<link rel="stylesheet" href="{% static 'investors/css/investors.css' %}">
	
{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/navbar.html" %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    {% if messages %}
                        {% for message in messages %}
                            <section class="alert {{message.tags}}">
                                {{message}}
            
                            </section>
                        {% endfor %}
                    {% endif %}
                    <div class="col-md-3">
                        <img src="{{ company.logo.url}}" class="foto-empresa" alt="">
                    </div>
                    <div class="col-md">
                        <h3>{{company.name}}</h3>
                        <span class="badge bg-primary">{{company.get_area_display}}</span>
                    </div>
                    
                </div>
                <br><br>
                <div class="progress" wtyle="80%">
                    <div class="progress-bar bg-primary"
                         style="width: {{ percentual_sold }}%"></div>
                </div>
                <br>
                    {% if concretizado %}
                        <span class="badge bg-success">V</span><span>&nbsp &nbsp A empresa já atingiu 80% do percentual captado, portanto seu investimento será concretizado.</span>
                    {% else %}
                        <span class="badge bg-warning">x</span><span>&nbsp &nbsp Seu investimento será concretizado caso a empresa atinja pelo meno 80% do valor esperado até a data final.</span>
                   {% endif %}
                <hr>
                <p>{{company.description}}</p>
                <div class="col-md">
                    <h5>Valuation esperado</h5>
                    <span class="sub-fonte">Esperado: {{company.valuation}}</span>
                    <br>
                    <br>
                    <h5>Percentual</h5>
                    <span class="sub-fonte">Total a venda: {{company.percentual_equity}}%</span>
                    <br>
                    <span class="sub-fonte">Disponivel à compra: {{ percentual_disponivel }}%</span>
                </div>
                <br>
                <span class="badge bg-warning">{{company.target_audicence}}</span>
                <br><br>
                <h4 style="color: #92D5EB">Indicadores |</h4>
                
                <div class="row">
                    {% for metric in metrics %}
                        <div class="col-md-3" >
                            <div class="dark-color" style="padding: 20px; text-align: center;">
                                <h5>{{ metric.title }}</h5>
                                <h6>R$ {{ metric.value }}</h6>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <hr>
                <div class="row">
                    <h4>Faça sua proposta</h4>
                    <br><br>
                    <div class="col-md">
                        <form action="{% url "make_proposal" company.id %}" method="POST"> {% csrf_token %}
                            <input type="number" name="value" class="form-control" placeholder="Valor para investir">
                            <br>
                            <input type="submit" class="btn btn-indigo-normal" value="Salvar">
                    </div>
                    <div class="col-md">
                            <input type="number" name="percentual" class="form-control" placeholder="Percentual desejado">
                        </form>
                    </div>
                    
                </div>
            </div>
            <div class="col-md-5 intereses-investimentos">
                <video name='demo' controls autoplay width='100%'>
                    <source src="{{company.pitch.url}}" type="video/mp4"></source>
                </video>

                <hr>
                    {% for document in documents %}
                        <div class="list_documentos">
                            <div class="row">
                                <div class="col-md-2" style="text-align: center">
                                    <a href="{{ document.file.url }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" style="color: white;" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                                            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
                                            <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
                                        </svg>
                                    </a>
                                    
                                </div>
                                <div class="col-md-6">{{ document.title }}</div>
                                <div class="col-md-4" style="text-align: right;">
                                    
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            </div>
        </div>
    </div>
    <br><br>
{% endblock 'body' %}

investors/templates/sign_contract.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

<link rel="stylesheet" href="{% static 'businessman/css/list_companies.css' %}">
<link rel="stylesheet" href="{% static 'businessman/css/company_details.css' %}">
<link rel="stylesheet" href="{% static 'users/css/users.css' %}">
<link rel="stylesheet" href="{% static 'investors/css/investors.css' %}">
	

{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/navbar.html" %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    {% if messages %}
                        {% for message in messages %}
                            <section class="alert {{message.tags}}">
                                {{message}}
            
                            </section>
                        {% endfor %}
                    {% endif %}
                    <div class="col-md-3">
                        <img src="{{ inv_prop.company.logo.url }}" class="foto-empresa" alt="">
                    </div>
                    <div class="col-md">
                        <h3>Assinar contrato</h3>
                    </div>
                    
                </div>    
        </div>
        <div style="margin-top: 40px; padding: 20px" class="contrato dark-color">
            <h3>Contrato de investimento</h3>
            <p>Ao assinar esse contrato você concorda com todas as cláusulas abaixo</p>
            
            <ol>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
            </ol>

        </div>
        <form action="{% url 'sign_contract' id %}" enctype='multipart/form-data' method="POST" style="margin-top: 20px;"> {% csrf_token %}
            <input type="file" name="selfie" class="form-control" style="width: 40%">
            <br>
            <input type="file" name="rg" class="form-control" style="width: 40%">
            <br>
            <input type="submit" class="btn btn-indigo-normal" value="Assinar contrato">
        </form>
    </div>
    <br><br>
{% endblock 'body' %}

investors/templates/sugestions.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

<link rel="stylesheet" href="{% static 'businessman/css/list_companies.css' %}">
<link rel="stylesheet" href="{% static 'businessman/css/company_details.css' %}">
<link rel="stylesheet" href="{% static 'users/css/users.css' %}">
<link rel="stylesheet" href="{% static 'investors/css/investors.css' %}">

{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/navbar.html" %}
    <br><br>
    <div class="container">
        <div class="centralizar">
            <h2>Receba sugestões de empresas</h2>
            <p>Vamos analisar seu perfil e indicar as melhores opções de investimentos</p>
        </div>
        <br>
        <div class="dark-color cont-sugestao">
            <h3>Tipo de investidor</h3>
            <div style="width: 60%">
                <form action="{% url 'sugestions' %}" method="POST">{% csrf_token %}
                    <p>Selecione conservador caso busque investimentos de menos risco
                        e com menor retorno, selecione despojado se prefere correr mais riscos
                        e ter maiores possíbilidades de retorno.</p>
                    <select name="type" id="" class="form-select">
                        <option value="C">Conservador</option>
                        <option value="D">Despojado</option>
                        <option value="G">Genérico</option>
                    </select>
                    <br>
                    <h3>Áreas de interesses</h3>
                    <p>Selecione as áreas de mercado que possui interesse em investir</p>
                    <select name="area" id="" class="form-select" multiple>
                        {% for area in areas %}
                            <option value="{{area.0}}">{{area.1}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <h3>Valor que deseja investir</h3>
                    <p>Coloque o valor máximo que deseja investir</p>
                    <input type="number" name="value" class="form-control" placeholder="00,00">
                    <br>
                    <input type="submit" class="btn btn-indigo">
                </form>
            </div>
            
        </div>

        <br>
        <br>

        <div class="row">
            {% for company in companies %}
                <div class="col-md">
                    <div class="card dark-color" style="width: 18rem; border: none;" >
                        <img class="card-img-top dark-color" src="{{company.logo.url}}" alt="Card image cap">
                        <div class="card-body dark-color">
                        <h5 class="card-title">{{company.nome}}</h5>
                        <p class="card-text">{{company.descricao}}</p>
                        <a href="{% url "inspect_company" company.id %}" class="btn btn-indigo">Acessar</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock 'body' %}